#!/bin/bash
#

DEMO_HOME=`dirname $0`
DEMO_HOME=`cd $DEMO_HOME; pwd`

source $DEMO_HOME/functions.sh

usage_exit() {
        echo "Usage: $0 -c command [-t targets] [-u user]"
        echo
        echo "-e command: run adhoc command on [targets] nodes as [user]"
        echo
        exit 1
}

while getopts c:t:u:h OPT
do
    case $OPT in
        c)  CMD=$OPTARG
            ;;
        t)  TARGETS=$OPTARG
            ;;
        u)  MY_SSH_USER=$OPTARG
            ;;
        h)  usage_exit
            ;;
        *) usage_exit
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ "x$CMD" == "x" ]]; then
    usage_exit
fi

if [[ "x$TARGETS" == "x" ]]; then
    TARGETS="slaves"
fi

if [[ "x$MY_SSH_USER" == "x" ]]; then
    MY_SSH_USER=$SSH_USER
fi

echo
echo "Executing command [ $CMD ] on nodes [ $TARGETS ] as user [ $MY_SSH_USER ] ..."

echo
pdsh -l $MY_SSH_USER -R ssh -w ^$DEMO_HOME/conf/cluster/$TARGETS "$CMD"

echo
echo "DONE"
