#!/bin/bash
#

SCRIPT_DIR=`dirname $0`
SCRIPT_DIR=`cd $SCRIPT_DIR; pwd`

usage_exit() {
        echo "Usage: $0 -c command [-t targets] [-u user]"
        echo
        echo "-e command: run adhoc command on [targets] nodes as [user]"
        echo
        exit 1
}

while getopts c:t:u:h OPT
do
    case $OPT in
        c)  CMD=$OPTARG
            ;;
        t)  TARGETS=$OPTARG
            ;;
        u)  SSH_USER=$OPTARG
            ;;
        h)  usage_exit
            ;;
        *) usage_exit
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ "x$CMD" == "x" ]]; then
    usage_exit
fi

if [[ "x$TARGETS" == "x" ]]; then
    TARGETS="slaves"
fi

if [[ "x$SSH_USER" == "x" ]]; then
    SSH_USER="ubuntu"
fi

echo
echo "Executing command [ $CMD ] on nodes [ $TARGETS ] as user [ $SSH_USER ] ..."

echo
pdsh -l $SSH_USER -R ssh -w ^$SCRIPT_DIR/conf/cluster/$TARGETS "$CMD"

echo
echo "DONE"
