#!/bin/bash

umask 0022

DEMO_HOME=`dirname $0`
DEMO_HOME=`cd $DEMO_HOME; pwd`

source $DEMO_HOME/functions.sh

usage_exit() {
        echo "Usage: $0 [-c command] [-s subcommand] [-e command]"
        echo
        echo "-c command [-s subcommand]: run command on specific nodes"
        echo "Supported commands"
        # echo "  start-master-instances: start EC2 instances for hadoop masters"
        # echo "  start-slave-instances: start EC2 instances for hadoop slaves"
        # echo "  start-metastore: start RDS instance for HCatalog/Hive metastore"
        echo "  check-reachability: check reachability for all nodes"
        echo "  distribute-hdemo: distribute hdemo to all nodes"
        echo "  prepare: prepare for hadoop setup, runs on all nodes"
        echo "  setup-ambari-server: setup ambari server, run on ambari server"
        echo "  setup-ambari-agents: setup ambari agent, run on all nodes"
        echo "  setup-postgre: setup postgresql for metadb, run on ambari server"

        echo "  ambari-server: start / stop /status ambari server"
        echo "  ambari-agents: start / stop /status ambari agent"

        echo
        echo "-e command: run adhoc command on all nodes"
        echo
        exit 1
}

while getopts c:s:e:h OPT
do
    case $OPT in
        c)  CMD=$OPTARG
            ;;
        s)  SUBCMD=$OPTARG
            ;;
        e)  RUN_ON_ALL_NODES=1 && CMD=$OPTARG
            ;;
        h)  usage_exit
            ;;
        *) usage_exit
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ "x$CMD" == "x" ]]; then
    usage_exit
fi

# functions
function check-reachability() {
    for NODE in `cat $DEMO_HOME/conf/cluster/all-nodes`
    do
        ssh -p $HD_SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$NODE "exit" && echo "$NODE    OK"
        sleep 1
    done
}

function distribute-hdemo() {
    # Distribute setup bundle
    for NODE in `cat $DEMO_HOME/conf/cluster/all-nodes`
    do
        rsync -vzr -e "ssh -p $HD_SSH_PORT" --delete $DEMO_HOME/ $SSH_USER@$NODE:$HDEMO_REMOTE_HOME/
    done
}

function prepare() {
    distribute-hdemo

    CMD="sudo $HDEMO_REMOTE_HOME/prepare-env.sh"
    $DEMO_HOME/exec_cmd -c "$CMD" -t all-nodes
}

function setup-ambari-server() {
    CMD="sudo $HDEMO_REMOTE_HOME/setup-ambari-server.sh"
    $DEMO_HOME/exec_cmd -c "$CMD" -t ambari-server
}

function setup-ambari-agents() {
    CMD="sudo $HDEMO_REMOTE_HOME/setup-ambari-agent.sh"
    $DEMO_HOME/exec_cmd -c "$CMD" -t all-nodes
}

function setup-postgre() {
    CMD="sudo $HDEMO_REMOTE_HOME/setup-postgre.sh"
    $DEMO_HOME/exec_cmd -c "$CMD" -t ambari-server
}

function ambari-server() {
    if [[ "x$SUBCMD" == "x" ]]; then
        usage_exit
    fi

    case $SUBCMD in
        status )
            CMD="sudo ambari-server status"
            ;;
        start )
            CMD="sudo ambari-server start"
            ;;
        stop )
            CMD="sudo ambari-server stop"
            ;;
        * )
            usage_exit
            ;;
    esac

    $DEMO_HOME/exec_cmd -c "$CMD" -t ambari-server
}

function ambari-agents() {
    if [[ "x$SUBCMD" == "x" ]]; then
        usage_exit
    fi

    case $SUBCMD in
        status )
            CMD="sudo ambari-agent status"
            ;;
        start )
            CMD="sudo ambari-agent start"
            ;;
        stop )
            CMD="sudo ambari-agent stop"
            ;;
        * )
            usage_exit
            ;;
    esac

    $DEMO_HOME/exec_cmd -c "$CMD" -t all-nodes
}

# function start-master-instances() {
#     $DEMO_HOME/start-master-instances.sh
# }

# function start-slave-instances() {
#     $DEMO_HOME/start-slave-instances.sh
# }

# function start-metastore() {
#     $DEMO_HOME/start-metastore.sh
# }


function run_cmd_on_all_nodes() {
    if [[ $RUN_ON_ALL_NODES != 1 ]]; then
        usage_exit
    fi
    $DEMO_HOME/exec_cmd -c "$CMD" -t all-nodes
}


# main routine
case $CMD in
    check-reachability )
        check-reachability
        ;;
    distribute-hdemo )
        distribute-hdemo
        ;;
    prepare )
        prepare
        ;;
    setup-ambari-server )
        setup-ambari-server
        ;;
    setup-ambari-agents )
        setup-ambari-agents
        ;;
    setup-postgre )
        setup-postgre
        ;;
    ambari-server )
        ambari-server
        ;;
    ambari-agents )
        ambari-agents
        ;;
    * )
        run_cmd_on_all_nodes
        ;;
esac


